name: read-study-platform
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - pip
    - numpy=1.24.3
    - pillow=10.1.0
    - pip:
          - fastapi==0.104.1
          - uvicorn[standard]==0.24.0
          - gradio==4.7.1
          - python-dotenv==1.0.0
          - pydantic==2.5.0
          - aiosqlite==0.19.0
          - python-multipart==0.0.6
